# Generated by Django 5.0.2 on 2025-09-28 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("model_path", models.CharField(max_length=500)),
                ("processor_path", models.CharField(max_length=500)),
                (
                    "json_exact_match",
                    models.FloatField(
                        blank=True, help_text="% of exact JSON matches", null=True
                    ),
                ),
                (
                    "field_accuracy",
                    models.FloatField(
                        blank=True, help_text="% of correct fields", null=True
                    ),
                ),
                (
                    "row_recall",
                    models.FloatField(
                        blank=True,
                        help_text="% of table rows correctly extracted",
                        null=True,
                    ),
                ),
                (
                    "avg_inference_time",
                    models.FloatField(
                        blank=True,
                        help_text="Average inference time in seconds",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("testing", "Testing"),
                            ("archived", "Archived"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("is_production", models.BooleanField(default=False)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("inference_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documenttype",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_json", models.JSONField()),
                ("ground_truth_json", models.JSONField(blank=True, null=True)),
                ("is_exact_match", models.BooleanField(default=False)),
                ("field_matches", models.IntegerField(default=0)),
                ("total_fields", models.IntegerField(default=0)),
                (
                    "inference_time",
                    models.FloatField(help_text="Inference time in seconds"),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="training.trainedmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_prediction", models.JSONField()),
                ("corrected_data", models.JSONField()),
                ("correction_type", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainedmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "train_split",
                    models.FloatField(
                        default=0.8, help_text="Training data split ratio"
                    ),
                ),
                (
                    "val_split",
                    models.FloatField(
                        default=0.1, help_text="Validation data split ratio"
                    ),
                ),
                (
                    "test_split",
                    models.FloatField(default=0.1, help_text="Test data split ratio"),
                ),
                ("total_documents", models.IntegerField(default=0)),
                ("labeled_documents", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_model",
                    models.CharField(
                        default="naver-clova-ix/donut-base", max_length=200
                    ),
                ),
                ("epochs", models.IntegerField(default=10)),
                ("batch_size", models.IntegerField(default=8)),
                ("learning_rate", models.FloatField(default=5e-05)),
                ("weight_decay", models.FloatField(default=0.01)),
                ("gradient_accumulation_steps", models.IntegerField(default=1)),
                (
                    "image_size",
                    models.IntegerField(
                        default=1280, help_text="Max dimension for image resize"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing Data"),
                            ("training", "Training"),
                            ("evaluating", "Evaluating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_epoch", models.IntegerField(default=0)),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(blank=True, null=True)),
                ("train_loss", models.FloatField(blank=True, null=True)),
                ("val_loss", models.FloatField(blank=True, null=True)),
                ("best_val_loss", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("model_path", models.CharField(blank=True, max_length=500)),
                ("processor_path", models.CharField(blank=True, max_length=500)),
                ("training_logs", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingdataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="training_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="training.trainingjob"
            ),
        ),
        migrations.CreateModel(
            name="TrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epoch", models.IntegerField()),
                ("step", models.IntegerField()),
                ("loss", models.FloatField()),
                ("learning_rate", models.FloatField()),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "training_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="training.trainingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="trainedmodel",
            unique_together={("document_type", "version")},
        ),
    ]
