# Generated by Django 5.0.2 on 2025-10-06 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this API key", max_length=200
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 characters of key (for display)",
                        max_length=8,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA256 hash of the full key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=1000, help_text="Max requests per hour"
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                (
                    "allowed_models",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Models this key can access (empty = all models)",
                        related_name="api_keys",
                        to="training.trainedmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
